### ISSUE TITLE
replaceTitle not working with RegExp

### ISSUE THREAD

**Issue by princemaxwell** [MMM-CalendarExt2/MMM-CalendarExt2#110]
If you use replaceTitle normally, it's working fine:

`replaceTitle:[
	["abc", "def"]
]`

But, if you use RegExp, doesn`t matter what, no replacement is done, here i used the expample from  MMM-CalendarExt2/docs/Configuration/Calendar.md:

`replaceTitle:[
	["/([A-Z])([a-z]+ ?)/g", "$1"]
]`

Someone here with the same issue?

**Comment by klaernie** [comment]
Sorry, this is a bug in the documentation.
You need to remove the quotes around the RegExp:
```
replaceTitle:[ [/([A-Z])([a-z]+ ?)/g, "$1"] ]
```
With the quotes it just is a string, without them Javascript recognizes them as a RegExp and created an Object of the correct type.
