### ISSUE TITLE
Locale not completly taking into account

### ISSUE THREAD

**Issue by cisnard13** [MMM-CalendarExt2/MMM-CalendarExt2#111]
Hello,
In View part, I set Locale: "fr-FR". I displayed the daily mode and the text for today is "Today" and not "Aujourd'hui". Same thing for "Tomorrow".  After the days after are written in french correctly.

Thank you.
Cisnard13

**Comment by KristjanESPERANTO** [comment]
@cisnard13: You have to set `slotTitleFormat` in the view part. It's described [here](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/main/docs/Configuration/Views/daily.md).

**Comment by cisnard13** [comment]
@KristjanESPERANTO : thank you. It works perfectly
