### ISSUE TITLE
Upcoming view split in two columns

### ISSUE THREAD

**Issue by fideliopark** [MMM-CalendarExt2/MMM-CalendarExt2#116]
Hey. Perfekt modul. Thanks.

In my layout i have very less space in high.
So i setup two columns with upcoming events side by side.

How can i set up the second column to show upcoming event starting with the 6th from now on (the first 5 are shown in the first column)?

**Comment by klaernie** [comment]
Hi @fideliopark 

there is no builtin way to do this.

I think the easiest way would be to extend the [`View:assignEvents()`](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/master/CALEXT2_View.js#L38) with a new config attribute `skipItems` that works just like `maxItems`.
Feel free to implement this and send a pull request.

**Comment by fideliopark** [comment]
Had add new attribute skipItems and send pull request
