### ISSUE TITLE
MMM-CalenderExt2 needs to be ported away from the requests library

### ISSUE THREAD

**Issue by joekaiser** [MMM-CalendarExt2/MMM-CalendarExt2#126]
After following the steps in the README, MM will crash after restarting. The error is below. I have made sure to run `npm install` in this modules directory

```
1|mm  | [06.10.2021 12:31.37.803] [ERROR] 
1|mm  | WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
1|mm  | Require stack:
1|mm  | - /home/pi/MagicMirror/modules/MMM-CalendarExt2/node_helper.js
1|mm  | - /home/pi/MagicMirror/js/app.js
1|mm  | - /home/pi/MagicMirror/serveronly/index.js
```

**Comment by mpoxberry** [comment]
I ran into the same issue. I have had this running for a long time now. I updated to the latest version of MagicMirror 2.17.1 and wasn't able to get this module to start back up. Even tried upgrading to the latest version of node as well, still no luck.

**Comment by vwegert** [comment]
I believe adding the dependency is a temporary workaround at best. See https://github.com/MichMich/MagicMirror/issues/2468: The request module is deprecated entirely and should be replaced with node-fetch as far as I can tell.

**Comment by thanneman79** [comment]
> Have the same... Even i try [#126 (comment)](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/issues/126#issuecomment-939519870), electron load all module, but make a black screen when MMM-CalendarEXT2 load..

Been having this issue since early October and just finding this post now. Also having no luck with running "npm i request"

**Comment by thanneman79** [comment]
"npm i request" in the specific module worked for me. For others if you get the same error afterwards look closely at the new error as it may be for another module, in my case it was MyCommute, and I thought it was still CalendarExt.

**Comment by klaernie** [comment]
So, @vwegert said it correctly. We need to move away from using the requests library, and switch to something newer like node-fetch. But as I'm quite outside of the javascript space for a while I am not the most competent person to decide on the best option going forward.

I hope there's someone out there who knows what works best and can submit a pull request.
