### ISSUE TITLE
Unable to load on Windows MM2 install

### ISSUE THREAD

**Issue by ejdprops** [MMM-CalendarExt2/MMM-CalendarExt2#137]
recieved this error when cloning the repo:

$ git clone --depth=1 https://github.com/MMM-CalendarExt2/MMM-CalendarExt2
Cloning into 'MMM-CalendarExt2'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 53 (delta 2), reused 33 (delta 1), pack-reused 0
Receiving objects: 100% (53/53), 2.12 MiB | 8.15 MiB/s, done.
Resolving deltas: 100% (2/2), done.
error: invalid path 'docs/Tip:-Sync-with-MMM-Pages..md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

MMM-CalendarExt2 directory is empty except for the .git which has all the files I believe it's supposed to have, but npm install fails to install this module.

**Comment by KristjanESPERANTO** [comment]
There is already a PR for this issue: #130

Till it's fixed here, you could try to use my fork: https://github.com/KristjanESPERANTO/MMM-CalendarExt2

**Comment by KristjanESPERANTO** [comment]
@ejdprops Can you please check if your issue is solved with the new version?

**Comment by klaernie** [comment]
I guess not hearing anything indicates no further issue ;)
