### ISSUE TITLE
Translation for "Current" and "Upcoming"

### ISSUE THREAD

**Issue by 1Cedric1** [MMM-CalendarExt2/MMM-CalendarExt2#140]
Hello

and thank you for your work and the possibility of using your module.

May I ask you how to change the language of those 2 terms on the Mirror?

![langue](https://user-images.githubusercontent.com/61581150/154686781-c4b68c77-f707-4b52-92d5-6d43598a1b13.jpeg)

It seems that they are "hard coded", or I do not know how to show it in the right language.

Thank you for your interest and your Help.

Kind regards,

Cédric

**Comment by klaernie** [comment]
Hi @1Cedric1 !

Please take a look at https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/issues/79#issuecomment-627224236 - where would you expect that documented, so that you'd found it?

**Comment by 1Cedric1** [comment]
Thank you @klaernie, 
I will try it.
I suppose https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/master/docs/Localization.md is the right place to put this information, as it is in fact already the case.
Thank you very much for your job and have a good week-end.
