### ISSUE TITLE
Replace base64 dependency with built-in function of nodejs

### ISSUE THREAD

**Issue by KristjanESPERANTO** [MMM-CalendarExt2/MMM-CalendarExt2#144]
Since it is possible to implement base64 encoding with built-in nodejs functions, it would make sense to break free of this dependency (which last release was 2013).

I think that the implementation should not be so complicated. I just don't have a calendar with authentication on my MagicMirror to test it.

**Comment by TheGreyDiamond** [comment]
I've started to implement this, it needs a quick test from my side and then I'll be ready to make a PR.

**Comment by TheGreyDiamond** [comment]
Should be done in #148
