### ISSUE TITLE
Renaming default branch from master to main

### ISSUE THREAD

**Issue by KristjanESPERANTO** [MMM-CalendarExt2/MMM-CalendarExt2#146]
It is no longer common to call the default branch `master`, so I suggest changing it to `main`.

Here are instructions on how to do this: https://github.com/github/renaming#renaming-existing-branches

**Comment by klaernie** [comment]
I had that on my list - but didn't get to reading the github docs - seems they help with a load of redirects.
So now our default branch is `main`

**Comment by klaernie** [comment]
oh, and I did the same for the three plugins under this org

**Comment by klaernie** [comment]
According to [GitHub's own docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes) this is the best way to migrate to the new name:
```sh
$ git branch -m master main
$ git fetch origin
$ git branch -u origin/main main
$ git remote set-head origin -a
```
