### ISSUE TITLE
Unable to git pull to update - can't find remote ref

### ISSUE THREAD

**Issue by wenike** [MMM-CalendarExt2/MMM-CalendarExt2#149]
My mirror advised me that my version of this module was out of date so I went to do a git pull to update it. However, attempting to do so is giving me a message that there's a fatal error: couldn't find remote ref refs/head/smaster

**Comment by klaernie** [comment]
we renamed the default branch from `master` to `main`. See #146

**Comment by KristjanESPERANTO** [comment]
The easiest thing to fix this for your mirror would be to reinstall the module.

The second possibility would be to replace `master` with `main` (two times I think) in the file `.git/config`.

**Comment by klaernie** [comment]
According to [GitHub's own docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes) this is the best way:
```sh
$ git branch -m master main
$ git fetch origin
$ git branch -u origin/main main
$ git remote set-head origin -a
```
