### ISSUE TITLE
Is there a way to download a older build of the code?

### ISSUE THREAD

**Issue by pomtom44** [MMM-CalendarExt2/MMM-CalendarExt2#159]
Iv been having a few problems with my calendar which I think might be fixed with an update
(last update was 7 days ago where my system shows last update was over a year and a half ago)

The only problem is I have a few custom changes to the code, mainly the JS code which id want to keep

I didnt think to take notes of what I changed, and while I could go though and find it, i was wondering if there was a way to download files from back when I originally installed it, so I can compare and pull out my changes
Then re-apply them to the new code once I updated

**Comment by klaernie** [comment]
Hi @pomtom44 !

Did you download the code as a zip archive or did you did a `git clone ...`?
If it's the latter it's trivial.

Else I have a few ideas how to determine the version, so if you have the original zip you used to install the first time please upload that. I can't ensure you that we'll find it, but we might get close enough.

**Comment by pomtom44** [comment]
Wow, fast reply @klaernie, Thanks :)

Im farily sure i downloaded via ZIP, but not 100% sure
If I had the zip id just use that as it would be the original files, and compare that to my changes

I can see the last modified date / time for the files, and most of them are on the 28/09/2020
and the 4 files I have changed with dates between then and now
(the two main calext2 js and css files, and the event and view js files)

the css file im fairly sure was just me changing colors and borders so not too concerned about that, it would be the three js files where i made my own scrolling feature which id like to keep

**Comment by klaernie** [comment]
Well, I happened to see the notification and had a minute to spare. I'd suggest you make a fresh clone, than apply the `git rev-list` that https://www.endpointdev.com/blog/2014/05/git-checkout-at-specific-date/ neatly demonstrates, just do that with the date you found. That was a period where. Or mich happened in the repo, so your first guess will probably be right. 

Feel free to open a PR for your scrolling feature, but be aware that the last two weeks had quite a lot of reorganization, so it might be hard to apply a diff directly.

**Comment by klaernie** [comment]
Btw, a quick look suggests you downloaded this version: https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/tree/57fa7b522074951df7bf1e83db9471c896f941a3

**Comment by pomtom44** [comment]
That looks like its what im after :)
at least I can see changes which I would have made so assuming its close enough

Not sure if my code would be good enough to submit as a feature, it works for my setup, but the code is probably pretty bad and no idea how it would work with other layouts
