### ISSUE TITLE
Getting errors after updating to latest build

### ISSUE THREAD

**Issue by pomtom44** [MMM-CalendarExt2/MMM-CalendarExt2#160]
I updated my build to the latest version
(deleted the files and just re-downloaded the zip)
Then ran npm install, (no errors)
But when I load the page I get a bunch of errors and the calendar doesn't load

https://pastebin.com/BtLR1EWF

Not sure if I need to update something else?

**Comment by KristjanESPERANTO** [comment]
Can you show us your configuration of the module (without credentials, of course)? :slightly_smiling_face:

**Comment by pomtom44** [comment]
This is just the calendar part
https://pastebin.com/D5gLzwk8

Not sure if you need more then just that?

**Comment by KristjanESPERANTO** [comment]
What kind of calendars are these? I took your configuration and entered simple ics calendars as urls - that works so far.

Are you getting similar errors with this config: https://pastebin.com/e653MX7w ?

**Comment by klaernie** [comment]
The config looks totally fine to me - while you have quite a lot of calendars it's still fairly simply. And as you upgraded I doubt there'd be any problems with the calendar URLs.

Could that be a error while loading node-fetch? What version of node are you running? That log suspiciously points at node_helper.js line 6, which is the import of node-fetch.

**Comment by pomtom44** [comment]
@KristjanESPERANTO NextCloud exports, ICS downloads as far as im aware
Didnt have any problems before the update so something must have changed between then and now (then being 2 years ago when I first installed it)

@klaernie node -v shows 10.24.1 
Just realized that it is pretty old, but npm install didnt throw any errors so i didnt think to check on node versions
Do I need to upgrade that?

**Comment by klaernie** [comment]
mine is slightly newer:
```
root@xl-mm-7dc4fbfb8b-gvrhf:/opt/magic_mirror# node --version
v12.22.8
```
But I'm fortunate enough to run magic mirror in a docker container.
If you're fluent in running docker there might be a way to try running magic mirror inside a newer nodejs container.

**Comment by pomtom44** [comment]
Mine runs on a dedicated VM
(Old school docker, just havnt had the time to wrap my head around docker yet and migrate my stuff over to dockers)
Ill try upgrade node on it and see if it fixes the problem, as I dont have anything else on there which needs node so nothing else will really break

**Comment by pomtom44** [comment]
Ok yes, doing a force upgrade on node seemed to have fixed it
Must have been a new feature between 10 and 12 which was added
Upgraded to 16 as that was the latest stable which the updater found, and all seems okay

**Comment by klaernie** [comment]
Cool, happy to see it fixed. Don't worry about dockerizing, there are readymade containers for running magic-mirror out there.
If you need pointers, there's always a discussions tab up there, happy to share configs.
