### ISSUE TITLE
Events Stacked with Absolute Positioning

### ISSUE THREAD

**Issue by rliverman** [MMM-CalendarExt2/MMM-CalendarExt2#164]
I have the module up and running and "modes" such as "Daily" or any vertical list work fine. In "Monthly" or "Weekly" however all events on a given day are stacked on top of one another via the absolute positioning of timeline elements. Image of titles stacked is attached.

I haven't touched the core css or the custom css. Any reason this would occur? I also checked for any conflicts with other modules and restarted all systems.

I'm using the basic config here:
```js
    {
      module: "MMM-CalendarExt2",
      config: {
        calendars: [
          {
            url: URL,
            name: "Main Calendar",
            maxItems: 99,
            scanInterval: 10006030,
            beforeDays: 0,
            afterDays: 7,
            maxIterations: 999
          }
        ],
        views: [
          {
            mode: "week",
            position: "bottom_bar",
            slotCount: 1,
            timeFormat: "h:mm A",
            slotMaxHeight: "auto"
          }
        ],
        scenes: [
          {
            name: "DEFAULT"
          }
        ]
      }
    },
```
![Untitled-2](https://user-images.githubusercontent.com/1672872/157101605-337bb6c1-68a4-4a15-8893-88630a594d82.jpg)

**Comment by threesquare** [comment]
> 

thank you that fixed it.
