### ISSUE TITLE
Length of Notes

### ISSUE THREAD

**Issue by Robin-Hol** [MMM-CalendarExt2/MMM-CalendarExt2#169]
Hi, is possible to define a max length of the **notes** shown in appointments ?
I would like to cut off the notes after X characters. When multiple appointments are shown during a day, the list will be too long at the end.

If there is no variable for that to be set in the config file, can you provide me the part in your code that is responsible for displaying the notes ? 

[IMG_8724](https://user-images.githubusercontent.com/100868294/157431386-3792e549-2640-42a8-a330-5af3b5ffa4df.png)

**Comment by klaernie** [comment]
There is no config option for it, since that is handled by the CSS. I'd suggest you use the Chrome Devtools to pick out the element and the set `max-height` so a value that fits you.

**Comment by Robin-Hol** [comment]
Hi Andre, is it possible for you to tell me the element that is responsible for the height as I am not familiar with Chrome Dev Tools.

Furthermore the monitor is fitted inside a mirror. There is no access via browser or keyboard.

**Comment by Robin-Hol** [comment]
Thank you very much for your help.

**Comment by klaernie** [comment]
As this sounds like you could achieve your goal I'll close this issue. If I'm mistaken feel free to reopen this issue
