### ISSUE TITLE
Question about date format

### ISSUE THREAD

**Issue by 1Cedric1** [MMM-CalendarExt2/MMM-CalendarExt2#170]
Hello,
may I ask you where to switch month and day, e.g. 3/7 -> 7/3 or 07/03, on the first day of the month view?
![Sans titre](https://user-images.githubusercontent.com/61581150/157675859-75930dbf-72ce-4384-a8eb-7aaa0cc89739.jpeg)
Thank you for your interest and for your help.
Kind regards

**Comment by klaernie** [comment]
Did you read https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/main/docs/Localization.md ?

**Comment by KristjanESPERANTO** [comment]
`Do` is one token for "Day of Month".

Here you can see which token you can use: https://momentjs.com/docs/#/displaying/

I think `DD.MM.` or `DD/MM` for `slotAltTitleFormat` could be what you want.

```
        views: [
          {
            ...
            slotAltTitleFormat: "DD.MM."
          }
        ],
  ```

**Comment by 1Cedric1** [comment]
OK, Thank you very much!
Very much appreciated!
