### ISSUE TITLE
No custom.css file or call for one in getstyles function

### ISSUE THREAD

**Issue by dsisk559** [MMM-CalendarExt2/MMM-CalendarExt2#177]
When trying to set up custom CSS I noticed there is no custom.css file. Seeing its absence I created a custom.css file and added an override of:

`.CX2 .slot .slotHeader {
     background-color: blue !important;
}`

After restarting Magic Mirror there was no change in the slot header's background color. However, when I changed the color in the MMM-CalendarExt2.css file it did work.

After going through the MMM-CalendarExt2.js file I noticed it only includes the  MMM-CalendarExt2.css file in the returned array of the getstyles function.

In order to get custom.css to work, I had to add "custom.css" to the returned array of the getstyles function.

**Comment by klaernie** [comment]
`custom.css` refers to the central file that is included with Magic Mirror: https://docs.magicmirror.builders/modules/customcss.html

**Comment by dsisk559** [comment]
Oh, I didn't even think about that. Thanks for the info. I'll use that from now on.
