### ISSUE TITLE
MMM-CalendarExt2 "upcoming" "current" views do not display -- no errors

### ISSUE THREAD

**Issue by M1st3r-E** [MMM-CalendarExt2/MMM-CalendarExt2#178]
so i've recently installed this module and for the "month" "monthly" "week" "weekly" portion works well in the bottom_bar position...this said, i cannot add the "current" or "upcoming" on the top_left position (tried the middle_center but nogo)

followed and read alot on your gihub but alas nothing helps...here is my config
{
                 module: 'MMM-CalendarExt2',
                 config: {
                   calendars : [
                        {
                         name: "cal1",
                         /*icon: "noto-family-man-woman-girl-girl",*/
                         className: "class2",
                         scanInterval: 1000*60*5,
                         url: "calendar2.ics",
                         auth: {
                           method: "basic",
                           user: "username",
                           pass: "passwd",
                         },
                        },
                        {
                         name: "cal2",
                         /*icon: "emojione-flag-for-country",*/
                         className: "class1",
                         url: "calendar.ics",
                         auth: {
                           method: "basic",
                           user: "username",
                           pass: "passwd",
                         },
                        },
                   ],
                   views: [
                        {
                         /*name: "Today_View",*/
                         mode: "upcoming",
                         /*slotTitle: "Scheduled Today...",*/
                         position: "top_left",
                         positionOrder: 2,
                         maxItems: 6,
                         maxDays: 1,
                         hideOverflow: false,
                         filterPassedEvent: true,
                         calendars: ["cal1", "cal2"],
                        },
						{
                         name: "Weekly_View",
                         mode: "week",
                         title: "blabla",
                         position: "bottom_bar",
                         slotCount: 3,
                         slotMaxHeight: "50px",
                         slotSpaceRight: 3,
                         filterPassedEvent: true,
                         calendars: ["cal1", "cal2"],
                        },
                   ],
                   scenes: [
                        {
                         name: "View-Bottom-Bar",
                         views: ["Weekly_View"],
                        },
                        {
                         name: "View-Top-Left",
                         views: ["Today_View"],
                        },
                   ],
                 },
                },

**Comment by M1st3r-E** [comment]
can anyone take a look at this issue and give some insight??

**Comment by M1st3r-E** [comment]
nvm i figured it out on my own...

**Comment by KristjanESPERANTO** [comment]
Sorry, I have only now seen your issue. What was the cause of it?

**Comment by M1st3r-E** [comment]
using 2 scenes with 2 views (1 scene/view) was causing a display issue...dropped it to 1 scene and it was ok

**Comment by KristjanESPERANTO** [comment]
I haven't played with the font on the module yet, but check out the configuration of @klaernie ([here](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/main/docs/examples/klaernie.md)). He made changes to the font in it. Does that help you?

**Comment by M1st3r-E** [comment]
yeah thats exactly the config i followed but the options in the views do not work/apply....which leads me to think something else is configured or something else has been applied elsewhere....again i dont have errors for the module itself but the options seems to be bypassed soewhat!
