### ISSUE TITLE
*REQUEST* how to make calendar event colored according to title string found?

### ISSUE THREAD

**Issue by M1st3r-E** [MMM-CalendarExt2/MMM-CalendarExt2#179]
so i was able to add multiple calendars but one specific calendar is a shared calendar and cannot use the option --> .CX2 .event.sharedCalName and assign a color as all events will grab this same color.... i found that .event.[data-calendar-name="xx"] works for specific Cal names but this is by calendar.... i want to do this by calendar event and cannot find the appropriate string.... does this option even exist? if so, can someone provide it? tnx

**Comment by M1st3r-E** [comment]
does anyone have a guide to this or something?

**Comment by klaernie** [comment]
Did you try matching your event with a wildcard in `data-title=…`? https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

**Comment by M1st3r-E** [comment]
sorry i dont know what you mean....ill give you an example, an event beginning with 'M:' in title i want colored border solid pink,  an event beginning with 'E:' in title i want colored border solid blue, and so on...i wouldnt know how to code this!

**Comment by klaernie** [comment]
You're not missing much to get it working:
```css
.CX2 .event.FamCal[data-title^="E:"] {
  border-left: #00FFFF 5px solid;
}

.CX2 .event.FamCal[data-title^="M:"] {
  border-left: #FFFF00 5px solid;
}
```

Your original version was:
- checking the wrong attribute, `data-title` is the right one, `data-calendar-title` does not exist
- checking for equality, not if the title begins with your prefix. (That's why I linked https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors, as it explains it better than I ever could)

**Comment by M1st3r-E** [comment]
@klaernie tnx for your response...very appreciated, it worked well even though i dont know what it means :( ...what would the transform function bring to me that the CSS wouldnt? would it be a better alternative, and why? as well basically one last thing, so we covered if the title starts with either "E: or M:" but what if for anything else i want a background color and text color scheme, how would i code that? and whats the variable for text font? as i tried many but nothing applies! do i need the font somewhere local probably? tnx

**Comment by klaernie** [comment]
> would it be a better alternative?

Not necessarily. If you only want to do the prefix-matching you described CSS is perfectly adequate. But if you have conditions that make it more complex, for example nested conditions or conditions that form exceptions, you'll be much better off writing it in a true programming language that isn't as limited as CSS.

> what if for anything else i want a background color and text color scheme, how would i code that?

Just write more CSS rules, and maybe take a look at a course on how to use CSS.

> do i need the font somewhere local probably

If it's not one of the fonts available with MagicMirror you probably need to do something like we needed for Titillium Web:
https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/main/MMM-CalendarExt2.css#L1 (but it might be sufficient to copy the font files to the right place on your mirror installation)

---

In general: for all of these questions there are long answers, but you'll have much more fun by trying things out than by me telling you everything. Best suggestion: use the Chrome development tools on your non-mirror machine and play with that. It will make more things understandable if you can get feedback in realtime. See https://forum.magicmirror.builders/topic/13472/web-dev-tools for some nice pointers
