### ISSUE TITLE
deduplicateEventsOn confusion

### ISSUE THREAD

**Issue by SWDesertPenguin** [MMM-CalendarExt2/MMM-CalendarExt2#195]
I am having difficulties understanding how the deduplicateEventsOn works based on the documentation. I can get the configuration to make duplicated events not show; but how do I combine the entries under calendarName so the events show up “Bob/Jane/Sue/John” ? Or just “Everyone” ??

This is what I have that removes the duplication. Its at the very top of the module. Does it need to be somewhere else?

		{module: 'MMM-CalendarExt2',
			config: {
					rotateInterval: 45*1000,
					deduplicateEventsOn:["startDate","endDate","duration","title","location"],
					calendars: [

**Comment by klaernie** [comment]
If you take a look at my example config you'll find that there are 'virtual calendars' created, one for each combination of calendars.

Taking your example: if there's an event in the calendars for Bob and Jane that are identical, the calendar name of the resulting event will be `Bob|Jane`. So you need to include this combinated calendar in a view, else the view will reject the event and not display it.

**Comment by SWDesertPenguin** [comment]
Ah, that made things click. Thank you for the quick response

**Comment by klaernie** [comment]
If you have a way of explaining it in the documentation better then I did, please send a pull request. It's not easy to explain in general, so I struggled writing the docs.

**Comment by SWDesertPenguin** [comment]
The confusion on my part was not seeing an example of everything laid out, probably from staring at the configuration for too long.  I copied the whole configure for real usage and made a duplication example and submitted the pull request (hopefully correctly)
