### ISSUE TITLE
Double render on page change

### ISSUE THREAD

**Issue by themox** [MMM-CalendarExt2/MMM-CalendarExt2#198]
Using MMM-CalendarExt2 with MMM-Pages, and I fully acknowledge this issue could be with Pages and not CalendarExt2.  When the pages change, the render occurs twice.

Specifically, I am using the below code in the Calendar config, and I have rotate interval set to 0 within the Calendar.  Pages is set to a rotate interval and when it rotates, it sends a PAGE_INCREMENT notification which is received by Calendar.  This is all in accordance to the settings I found on one of these other pages for configuring Pages w/ Calendar.

                         "PAGE_INCREMENT" : {
                                exec: "sceneNext",
                        },

When the pages rotate, all of the calendar scenes double render - i.e. they flash like they are changing, and then flash again.  The other modules I am rotating amongst only render once, which is why I think this might be an issue with CalendarExt2.

I spent some time poking around in the JS files but am relatively new to the internals of these modules.  To be clear, on the page change it's the new page/scene that's rendering twice, not the old scene once and then the new scene.  Desired behavior is for the calendar to render only once.  Open to any suggestions for configuration or troubleshooting.

Config I am using below:
[config.txt](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/files/8578345/config.txt)

**Comment by themox** [comment]
@klaernie I figured this one out - recommend the following changes to the code:

In mmm-calendarext2.js, it currently shows this around line 273:

`  suspend() {
    this.showing = false;
    if (this.currentScene) {
      this.currentScene.clearViews();
    }
  },

  resume() {
    this.showing = true;
    if (this.currentScene) {
      this.work(this.currentSceneUid);
    } else {
      this.work();
    }
  },`

These functions assume that they wouldn't be called if the module didn't need them to be called which is not strictly true.  There are a number of cases where resume is called when it hasn't been suspended, for example.  In any case, I believe if you modify as per below by adding some error checking, it will solve these cases without breaking other cases.  I'm still building up my nerve to make an actual commit myself so recommending here.

`  suspend() {
 if (this.showing) {
   this.showing = false;
    if (this.currentScene) {
      this.currentScene.clearViews();
    }
}
  },

  resume() {
if (!this.showing){
    this.showing = true;
    if (this.currentScene) {
      this.work(this.currentSceneUid);
    } else {
      this.work();
    }
}
  },`

**Comment by klaernie** [comment]
Sounds good - could you put that into a pull request?

**Comment by themox** [comment]
Will do - will be my first time, so please be patient as I work through it.
