### ISSUE TITLE
Only displays 3 events for each slot (day)

### ISSUE THREAD

**Issue by alanrodriguezdotme** [MMM-CalendarExt2/MMM-CalendarExt2#245]
I'm only getting 3 events for each day, even though I don't have `maxSlots` set. I've tried other config options, but nothing seems to fix it.

Here's the config that I'm currently using:

```
{
	module: 'MMM-CalendarExt2',
	config: {
		calendars : [
			{
				name: "Family",
				url: "https://calendar.google.com/calendar/ical/***/basic.ics",
				scanInterval: 1000*60*60
			}
		],
		views: [
			{
				name: "Family Calendar",
				mode: "daily",
				position: "top_right",
				timeFormat: "h:mm A",
			},
		],
		scenes: [
			{
				name: "DEFAULT",
			},
		],
	},
}

**Comment by klaernie** [comment]
Does the log file show that it loaded all of the events?

**Comment by alanrodriguezdotme** [comment]
> Does the log file show that it loaded all of the events?

Yes, it shows it's loaded 875 events.
`[05.11.2022 15:26.39.684] [LOG]   [CALEXT2] calendar:Family >> Scanned: 875, Selected: 875`

I still only see 3 events each day when I run my MM project locally on my MacBook, as well as on the Raspberry Pi.

**Comment by skruglov2023** [comment]
If anyone else has this issue: set hideOverflow to false
