### ISSUE TITLE
Browse forward / Back

### ISSUE THREAD

**Issue by Nitecon** [MMM-CalendarExt2/MMM-CalendarExt2#246]
I love the calendar and use it as the standard full view of it but would like to increase functionality to allow for use of browsing forward / backward a month / week at a time, and also a select current date as default view.  Intent is to use home automation buttons like smartthings to call a webhook on magicmirror or something similar to create an event to trigger forward / backward paging actions.  

Will there be any intent to support pagination of the calendar by event?

**Comment by klaernie** [comment]
While that sounds like a neat idea I wonder how much code that requires to be working for multiple views at the same time.

So if you intend to maintain this long term go ahead, but I wouldn't guarantee my ability to maintain the feature in the future. 

Also one remark: I'd suggest to use the magic mirror standard notification system as input, so it would remain pluggable with other plugins.

**Comment by Nitecon** [comment]
Key there would just be a webhook that would increase by month / week nothing more complex than that, but that would require the date variable to be overridable for a period of time.

**Comment by klaernie** [comment]
See, the webhook might be appropriate for your use case. But someone else might use a magic mirror module that does GPIO, and would have buttons to switch. And someone else might use one of the gesture plugins to switch calendars.
