### ISSUE TITLE
Possible to display 12-hour time format?

### ISSUE THREAD

**Issue by dathbe** [MMM-CalendarExt2/MMM-CalendarExt2#332]
Is it possible to display the 12-hour time format (5:00 pm) instead of the default 24-hour format (17:00)?

**Comment by KristjanESPERANTO** [comment]
Try `timeFormat:"h:mm A",`.

https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/main/docs/Event-Time.md

**Comment by dathbe** [comment]
Thank you!  I promise I did look through the docs before posting.  But I'm new at this and did not see the Examples folder.

**Comment by KristjanESPERANTO** [comment]
No problem! It needs a bit time to get an overview.

Enjoy your mirror! 😃
