### ISSUE TITLE
Possible to hide details of events?

### ISSUE THREAD

**Issue by 1Cedric1** [MMM-CalendarExt2/MMM-CalendarExt2#335]
Dear @klaernie ,
thank you for providing this calendar module; it works fine and it is a pleasure to use it.
May I ask you if (and how) it is possible no to show (or to hide) the details of a Google event in you calendar?

For example only to show the subject, time and duration, but not the location or other details.

![Capture d’écran 2024-05-20 à 09 10 20](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/assets/61581150/c33ad5f6-d7fe-4d71-8c27-b5bd0cb9bd9d)

Thank you in advance for your advice and have a good day. Kind retards, Cedric

**Comment by klaernie** [comment]
The simplest way is to include this in your CSS:
```css
.CX2 .eventSub {
    display: none;
}
```

This simply hides all the details.

**Comment by 1Cedric1** [comment]
Perfect, I will try, thank you very much!
