### ISSUE TITLE
Completely transparent background

### ISSUE THREAD

**Issue by ems522** [MMM-CalendarExt2/MMM-CalendarExt2#356]
I currently have 3 views (today, upcoming (today and next 3 days), and then monthly).
The calendar is on the left side, and then on right side i have clock, weather and a few other modules.
I am simply using a white background and the right side looks good, however the calendar has a gray background, and almost looks like it fades some.  Regardless, I just want to have a transparent or white background for the calendar, with a black border.
Any ideas?

**Comment by ems522** [comment]
In the config file i created 3 different views and gave them a className.  

- dailyViewClass
- upcomingViewClass
- monthlyViewClass

I reference those classes in the custom.css and can apply some formatting to them, and even change the background, however i want the background to basically be 'invisible'.  I have the .CX2 background set to white, so i just want the calendar views to have a solid white background as well and then add a border.  but nothing seems to work when trying to set it to transparent or white.  Instead it's almost like a gray or like a black faded into a white.  Here's a sample of code I am using.  

.CX2 .view.dailyViewClass{
  width: 50%;
  border: none;
  background-color: white;
  
}

**Comment by KristjanESPERANTO** [comment]
Try this in your `custom.css`:

```css
.CX2 .slot > .slotContent {
    background-image: none;
}
```

**Comment by ems522** [comment]
Alright so that did give it a white background, but now just need to give my views a border.  I tried a few things but nothing works.  Here's how it looks currently with your update.  This is the monthly view:

![image](https://github.com/user-attachments/assets/8eadaeb1-b8f5-4fa0-806b-4fe96c1fb57e)

**Comment by ems522** [comment]
So I want to give the view a border (left, right, and bottom)

**Comment by ems522** [comment]
Alright so for the Daily and Upcoming views, it gave me a gray-ish border on the top, left, and bottom. But no border on the right.
For the Monthly view, it gave me Left border, top, and a right border for just the calendar title, but no other part of the calendar on the right.  Also there are none in netween the days.  I imagine this would be .CX .view.row?

**Comment by KristjanESPERANTO** [comment]
I can't reproduce this. Please provide your configuration of the module (without calendar URLs, of course).

**Comment by ems522** [comment]
and here's my custom.css:

```
.MMM-CalendarExt2{
  width: 79%; /* Adjust width as needed*/
  max-width: 100%; /* Prevent overflow */
  max-height: 1100px; /*Adjust this value to your preferred height */
  /*overflow-y: auto; /*Allows scrolling if content exceeds max-height*/
  position: fixed; /* Keep it in position */
  /*right: 0; /* Align to the right */ 
  left: 20px; 
  top: 0; /*Align to the top */
  z-index: 9999; /* Ensure it appears on top */
  background-color: rgba(0, 0, 0, 1); /*Optional: semi-transparent background */
  color: white; /* Optional: text color */
  margin-bottom: 100px; /*Adjust based on height of your bottom bar */
    /*border-bottom: 2px solid #ffffff;*/
}

/* Adjust inner elements if needed */
.MMM-CalendarExt2 .your-inner-element {
  /* Add styles specific to inner elements, if necessary */
}

/*attempting to format entire MMM-CalendarExt2 module*/
.CX2 {
  background-color: white;
 
}
/*attempting to format the slots within the module to white*/ 
.CX2 .slot {
  background-color:white;
}

.CX2 .cellSlot.weekday_6 .slotSubTitle {
  color: red;
}

.CX2 .cellSlot.weekday_7 .slotSubTitle {
  color: red;
}


/*Daily View Formatting*/
/*formatting the daily view from config.js*/
.CX2 .view.dailyViewClass{
  width: 50%;
  background-color: white;
  
}



 /*Monthly View Formatting*/ 
.CX2 .monthViewTitle{
  background-color: white;
  color: black;
  text-align: center;
}
.CX2 .view.monthlyViewClass{
  
  background-color: hsl(163, 15%, 91%);
  max-height: 1075px;
}

/*Upcoming View Formatting*/
.CX2 .view.upcomingViewClass{
  width: 50%;
  background-color: hsl(163, 15%, 91%);
  
}

 /*Clock Module Formatting*/
 .module.clock .time{
  color: #82bae5;
 }
 .module.clock .date{
  color: #82bae5;
 }
 .clock .dimmed{
  color: #82bae5 !important;
 } 
 .clock .module-content{
  color: #82bae5 !important;
 }

 /*Weather Module Formatting*/
 .weather .bright{
  color: #82bae5;
 }
 .weather .module-content{
  color: #82bae5 !important;
 }
 .weather .dimmed{
  color: #82bae5;
 }
 .module.weather .weather-current{
  color: #82bae5;
 }
 .weather .module-header{
  color: #82bae5 !important;
 } 
 .weather.normal .medium{
  color: #82bae5 !important;
 }

 /*Formatting everything in the 'right' regions*/
 .region .right{
  color: #82bae5 !important;
 }
 
 /*MMM-NFL Module Custom Formatting*/ 
 .MMM-NFL .module-content{
  color: #82bae5 !important;
 } 
 /*MMM-NHL Module Custom Formatting*/
 .MMM-NHL .module-content{
  color: #82bae5 !important;
 } 

 .CX2 .slot > .slotContent {
  background-image: none;
  
}
.CX2 .view.column {
  border-style: solid;
}
```

**Comment by ems522** [comment]
the entire Magic Mirror to be white is fine as well.  I have a few modules on the right hand side as you can probably see from the code i sent, and then the CX2 calendar module (3 different views).  I have formatted events (transform based on conditions), and that's working properly,  Just want everything else to be white/transparent, as I think it would make it more legible.

**Comment by ems522** [comment]
actually I may have figured out the issue...i think an update was preventing something from saving/deploying.  Now it appears the border is working somewhat.  ill keep playing around with it and let you know - thanks!

**Comment by KristjanESPERANTO** [comment]
Nice! If you are happy with the result, feel free to post a screenshot here. It would be interesting to see what your white background concept looks like in the end :slightly_smiling_face: 

And feel free to reopen this issue if there are outstanding issues.
