### ISSUE TITLE
MMM-CalenderExt2 views get multiplied if using MMM-ProfileSwitcher

### ISSUE THREAD

**Issue by Tom-Hirschberger** [MMM-CalendarExt2/MMM-CalendarExt2#65]
If i use MMM-ProfileSwticher to switch between scenes a new DOM element is created each time i switch the profile.

**Comment by Tom-Hirschberger** [comment]
I figured the problem out and created a pull request.
Additionally changing to scene with index 0 was not possible and is fixed now

**Comment by Tom-Hirschberger** [comment]
The change with MMM-ProfileSwitcher is not very smooth at the moment because MMM-ProfileSwitcher initiates an resume() before the change happens. Because of this MMM-CalenderExt2 first draws the old scene and then changes directly to the new one.
The time gap is so small that the objects of the old draw are still present when the new one is added.

I only found a bad way suppressing this behavior by introducing a new boolean variable which prevents the resume method from calling work if the change method is called. But this might be a problem with other modules. I did not check this one in

**Comment by klaernie** [comment]
I don't know, if we should keep this issue around - from my perspective I don't know how to fix that interaction the right way, as I don't even know how these two modules are wired together.

@Tom-Hirschberger What do you think? Is the userbase for MMM-ProfileSwitcher using CalendarExt2 much larger than just you?

**Comment by Tom-Hirschberger** [comment]
@klaernie You are right. I think with the merge of my branch the duplication got fixed. The flickering ist not such a big problem. I will try to optimize it if i got time
