### ISSUE TITLE
12 hour time and background

### ISSUE THREAD

**Issue by joshuaandrewsN** [MMM-CalendarExt2/MMM-CalendarExt2#70]
Two quick issues (I hope)

Is there a way to show the event time with a 12-hour clock?

And is there a way to add a transparent background to the entire calendar to make it easier to read when there is a background image?

Like https://forum.magicmirror.builders/topic/9168/how-add-transparent-background-to-modules/10

Thanks for the great module!

**Comment by eouia** [comment]
> Is there a way to show the event time with a 12-hour clock?

https://github.com/eouia/MMM-CalendarExt2/wiki/Event-Time

> And is there a way to add a transparent background to the entire calendar to make it easier to read when there is a background image?

Hmmm, half-transparent objects would become harder to read over the background-image. Don't you agree?
Anyway, You can adjust anything you want by controlling CSS.
https://github.com/eouia/MMM-CalendarExt2/wiki/4.-Styling
Look inside https://github.com/eouia/MMM-CalendarExt2/blob/master/MMM-CalendarExt2.css , and find what you want to change, then override it into `css/custom.css` of your magicmirror.

**Comment by joshuaandrewsN** [comment]
Ok I edited /MMM-CalendarExt2.js and chaned it to h:mm A for all times.  Is there a way to do that in custom.css in case the app is updated?

>half-transparent objects would become harder to read over the background-image. 

What I really want is a mostly-solid black background behind the calendar to ensure it is readable when other objects are behind it, but I can't seem to make a background work for the whole calendar module or region.

**Comment by eouia** [comment]
> I edited /MMM-CalendarExt2.js and chaned it to h:mm A for all times

??? You don't need to modify source itself. Just assign `timeFormat`, `dateFormat`, `dateTimeFormat` (Which you need) for views in configuration(config.js)


To make whatever CalendarExt2 things transparent, add this into your `css/custom.css`
```css
.CX2 {
  opacity: 0.5;
}
```
But I recommend to control for each sub-objects more detaily.

**Comment by joshuaandrewsN** [comment]
>Just assign timeFormat, dateFormat, dateTimeFormat (Which you need) for views in configuration(config.js)

I don't see how that would be possible, is there an example of using that?

**Comment by eouia** [comment]
insert into your target view configuration.


like this;
```js
views: [
      {
        name: "MY_TARGET_VIEW",
        mode: "daily",
        title: "My daily",
        calendars: ["..."],
        slotCount: 4,
        timeFormat: "h : mm a", //<- like this.
      },
     ....
```
This example will change only `time`, if you need,  add `dateFormat` or `dateTimeFormat`.
https://github.com/eouia/MMM-CalendarExt2/wiki/Event-Time

**Comment by joshuaandrewsN** [comment]
Thanks.  I still can't get the background to be anything when there is not an event (the titles, the days) but the time in 12hr is working.

**Comment by klaernie** [comment]
@joshuaandrewsN upon reading this, I keep wondering: What is your current background? The forum post you linked showed how to apply a solid color with transperancy, but that wouldn't be visible if the background is black like in the default magic mirror config.

Could you please post a screenshot and your config?

**Comment by joshuaandrewsN** [comment]
The problem is I have MMM-GooglePhotos on top and MMM-CalendarExt2 in the middle.  When the calendar grows from too many events it creeps up on to the photos and then is usually unreadable.  I want the calendar to be readable even when it slides onto MMM-GooglePhotos but nothing seems to do that.

I did move the middle section down, which helps.  A bigger problem is the calendar displays deleted iCloud items, but I haven't researched that yet.

I'll attached an image, but there are not enough events currently to push the calendar up.

![IMG_5947](https://user-images.githubusercontent.com/56892460/82508099-07a0a680-9ad2-11ea-9959-ffb73341a429.JPG)

               {
                        module: "MMM-GooglePhotos",
                        position: "top_bar",
                        config: {
                                albums: ["WallPi"], // Set your album name. like ["My wedding", "family share", "Travle to Paris"]
                                updateInterval: 1000 * 45, // minimum 10 seconds.
                                sort: "random", // "old", "random"
                                uploadAlbum: null, // Only album created by `create_uploadable_album.js`.
                                condition: {
                                        minHeight: 400, // Or 400
                                },
                                showWidth: 1080, // These values will be used for quality of downloaded photos to show. real size to show in your MagicMirror region is recommende$
                                showHeight: 720,
                                timeFormat: "YYYY/MM/DD HH:mm", // Or `relative` can be used.
                        }
                },
                {
                        module: "MMM-CalendarExt2",
                        config: {
                                rotateInterval: 90*1000,
                                scenes:[
                                        {
                                                name: "DEFAULT",
                                                views: ["Family"],
                                        },
                                ],
                                views:[
                                        {
                                                name: "Family",
                                                title: "Family Calendars",
                                                mode: "daily",
                                                type: "column",
                                                position: "middle_center",
                                                slotCount: 5,
                                                //slotMaxHeight: 250,
                                                locale: "en",
                                                timeFormat: "h : mm a",
                                                hideOverflow: false,
                                                filterPassedEvent: true,
                                                calendars: ["iCloud"],
                                        },
                                ],
                                calendars: [

**Comment by klaernie** [comment]
I think the easiest fix would be this in `custom.css`:
```css
.CX2 {
    background: #000000d9;
}
```

This isn't the prettiest solution, but I think you could make it a bit prettier with additionally specifying a `padding: 10px;` or rather rounded with `border: solid #00000000 10px; border-radius: 10px;`
