### ISSUE TITLE
invalid line (no token ";" or ":") <!DOCTYPE html>

### ISSUE THREAD

**Issue by opxcode** [MMM-CalendarExt2/MMM-CalendarExt2#71]
Not sure if i'm doing something wrong? 
downloaded the ical: https://www.calendarlabs.com/ical-calendar/holidays/singapore-holidays-67/
{name:"SG2020"
url:"http://localhost:8080/modules/calendar/Singapore_Holidays.ics"}
but it's not reading it.

**Comment by eouia** [comment]
I don't know what you did something wrong without more detailed information.

**Comment by klaernie** [comment]
@opxcode Could you please paste the exakt config you used?

**Comment by klaernie** [comment]
feel free to reopen with the config

**Comment by LukasGrebe** [comment]
For any future reference: I had a similar problem. (Found this when googling that same error message)

My problem was the input file not being an ical/ics file but an html error page. Loading the ics from a remote server actually returned a 502 Http Error (see below)

this might be similar as the first line appears to be "<!DOCTYPE html>" and not contain a : or ; 

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
```
