### ISSUE TITLE
Month Mode not showing correctly in full screen

### ISSUE THREAD

**Issue by WaltmanBeta** [MMM-CalendarExt2/MMM-CalendarExt2#75]
I am really liking this module! I have been playing with it for a while and have everything setup except when I display in "month" mode the display does not show the entire month nor is it centered as seen below and all of this is with default CSS so that is not the problem. I have also included the config for "views" section.
![Default CSS](https://user-images.githubusercontent.com/30900832/81331289-5d576680-906f-11ea-8278-ea3ac7ae3831.JPG)
```
views:[
  {
  name: "Month View",
  position: "fullscreen_below",
  mode: "month",
  slotAltTitleFormat: "MMM D",
  },
],
```
So far I have been able to figure out how to center the view horizontally, change some event colors and remove the  week-marks just by adding a few minor custom.css lines. These lines can be seen below along with picture still showing the top of the month not displayed. 
```
.fullscreen .CX2 {
  left:0px;
}
.CX2 .weeksmark {
  display: none;
}
```
![Custom CSS ON](https://user-images.githubusercontent.com/30900832/81332231-b70c6080-9070-11ea-9f9d-6ca360eefa23.JPG)

That being said I am still not able to figure out how to actually show the entire month. The final display I am planning on using is a 720p TV (I am dissembling it to make a frame around the screen while also slimming down depth but maintaining the smart features for the wife's Netflix). The actual resolution of the screen according to the RPi is 1366x768. I am still new to CSS so i am really looking for any help.

**Comment by klaernie** [comment]
Hi @WaltmanBeta 

first of all I don't think `fullscreen_below` is the region you really want to use. It is hardcoded on all four sides in the `main.css`. I suggest you use `top_bar` or `bottom_bar` - that allows the module to adjust in size in at least one direction.

Than your resolution is pretty low - sadly I understand that problem too well. I arranged with the fact, that an entire 7 day week wouldn't fit into my screen, so I reduced that to 5 days to keep the event names readable.

If I emulate your resolution on my desktop I see that some things are getting cut off or overdrawn by other elements. I notice you have some module in the top and bottom of the screen (the clock and what looks like page markers). Possibly they reduce the available resolution to the calendar as well.

Finally: In your first image I saw that actually 4 week numbers were shown - in your second image the week number was missing as you wanted to hide them.

This all leads me to these recommendations:
- increase the screen size if you have the means or
- downsize what you show

The latter is probably easier to achieve (I actually tried the "Honey, I need a bigger TV for that pretty gimmick!" route, now we have a 34" flat ultrawidescreen in our hallway ;) ).

So for downsizing I have a few ideas:
- consider what you really care about. For me it was the next couple days. A month from now was not really needed.
- if you only have 1 or two events a day reduce `slotMaxHeight` to below the default `150px`, so less space is wasted.

**Comment by BertoBoushae** [comment]
@klaernie 
I have a question.
I set up my magic mirror following all documentation. But I am having an issue with the MMM-Calendarext2 module. I configured it how I want but I can't seem to get the monthly calendar in the bottom_bar, it just covers the whole screen layered on top of the other modules. Any help or direction would be helpful. Thanks!

I want it to look exactly like the example they have here:

https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/master/doc/Configuration.md

Here is my code:

module: 'MMM-CalendarExt2',
  config: {
    calendars : [
      {
	name: "Jolliffe Activities",
        url: "https://calendar.google.com/calendar/ical/ //took out the 
         rest of url.
      },
    ],
    views: [
      {
        mode: "upcoming",
	position:"top_left",
	title: "Jolliffe Upcoming Activities",
      },
	{
	mode: "month",
	position: "bottom_bar",
	title: "Jolliffe Monthly Activities",
	slotSubTitleFormat: "dddd",
	slotMaxHeight: "120px",
	monthFormat: "[Month:]MM",
	
	},
    ],
    scenes: [
      {
        name: "DEFAULT",
	views: [],
      },
    ],
  },
},

**Comment by klaernie** [comment]
@BertoBoushae could you please open a separate issue for that? I don't like mixing different problems in one issue, that makes following conversations for everybody harder.
