### ISSUE TITLE
Upcoming only showing 4 items

### ISSUE THREAD

**Issue by smartroad** [MMM-CalendarExt2/MMM-CalendarExt2#77]
Trying to use the Upcoming view but it only shows 4 slots and thats it. I've tried using slotcount to 15 but doesn't do anything.

**Comment by klaernie** [comment]
`slotcount` isn't used by the upcoming view. There you'd probably want to use `maxItems`.

**Comment by smartroad** [comment]
> `slotcount` isn't used by the upcoming view. There you'd probably want to use `maxItems`.

Thanks for the reply, I have used maxItems as well, I still only get 4 items showing with a +11 in the bottom right. Below is the code in the config file for that view I am using:
`{
						name: "Upcoming Events",
						mode: "upcoming",
						position: "top_left",
						useEventTimeRelative: false,
						maxDays: 365,
						maxItems: 15,
					}, `

**Comment by klaernie** [comment]
Okay, after reading through the code I found the missing piece: You did not override the default of `hideOverflow`. With `hideOverflow` set to the default `true` the `slotMaxHeight` (default `150px`) comes into effect, which hides all events that do not fit into that `150px` high window.

If you have practically unlimited space underneath you could set `hideOverflow: false`, which doesn't hide anything, but if you have something below the Upcoming Events you should instead specify `slotMaxHeight: 300px` (I would presume that shows than about 8 events with your CSS).
