### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by klaernie** [MMM-CalendarExt2/MMM-CalendarExt2#78]
Hi @eouia 

As as I use CalendarExt2 and already have a bit of experience working in it’s internals I want to offer my help maintaining it. But of cause I know that I am neither a JS pro like you nor that I could ever reach your level of dedication. 

I mainly would hope that there are more skilled people that could do this better than me.

Maybe moving your MM Modules to a separate org and find more people to co-maintain many of them could be an approach. 

Thanks for your dedication and hard work. I have seen in many issues that your support exceeds what many companies provide as paid support!

Best regards, Andre

**Comment by eouia** [comment]
Thanks for your suggestion. But anyway at least one moderator of org be needed and I couldn't.

**Comment by klaernie** [comment]
I was thinking, that you might make it one org for all your plugins. For some you already found maintainers. 

Nevertheless I volunteer to maintain CalendarExt2.

**Comment by eouia** [comment]
Give me your forum Id (if exists). 
And if you already have a fork of these modules in your account, remove them and tell me.
You can make an org and move them into it afterwards.

**Comment by klaernie** [comment]
Just created a forum account named identical to my GitHub handle `klaernie`. My fork is out of the way, but you also could transfer it also directly to org `MMM-CalendarExt2`.

**Comment by klaernie** [comment]
@eouia thanks for transferring. I hope to be a useful maintainer!
