### ISSUE TITLE
Translation does not work completely

### ISSUE THREAD

**Issue by M3taKn1ght** [MMM-CalendarExt2/MMM-CalendarExt2#79]
Hi there,

I just at your module to my MMM, but the translation to other languages than "en" didn't work to 100%.
So in "Today" and "Tomorrow" in the views will not translate, I only see the view.
Tested with fr, de, nl and it.
Is there a way to fix this?

**Comment by eouia** [comment]
https://github.com/eouia/MMM-CalendarExt2/wiki/Localization

**Comment by M3taKn1ght** [comment]
I tried this but it still not work. "Today" and "Tomorrow" is only viewed in english

**Comment by eouia** [comment]
What's your default locale and what is done in config.js and what to expect? tell me more details.
Show your configuration about this module.

**Comment by M3taKn1ght** [comment]
So my default-language is de-DE,
in all my config I define "de.DE" like in your Wiki. Also I changed the config for the views with german. But the result is the same, in the button_bar an the config looks like below:
 		{
			module: "MMM-CalendarExt2",
			config: {
					locale: "de-DE",
					calendars: [
						{
							name: "Joern Privat",
							beforeDays: 10,
							afterDays: 30,
							scanInterval: 1000*60*5,
							url: ,
							icon: "fa-solid:swimmer",
							className: "Joern",
						},
						{
							name: "Zelda Multi",
							beforeDays: 10,
							afterDays: 30,
							scanInterval: 1000*60*5,
							url: 
							icon: "emojione-monotone:family-man-woman-girl-boy",
							className: "Zelda",
						},
						{
							name: "Nora Work",
							beforeDays: 10,
							afterDays: 30,
							scanInterval: 1000*60*5,
							url: ,
							icon: "fa-solid:laptop-house",
							className: "Nora",
						},
					],
					views:[
						{
							name: "Overview Private",
							title: "Aktuelle Termine",
							mode: "daily",
							type: "row",
							position: "bottom_bar",
							slotCount: 5,
							locale: "de-DE",
							hideOverflow: false,
							filterPassedEvent: true,
							dateFormat: "MM/Do",
							dateTimeFormat:{
								sameDay: "[Heute] HH:mm",
								nextDay: "[Morgen] HH:mm"
							},
							calendars: ["Joern Privat","Zelda Multi","Nora Work"],
						},
					],
					scenes:[
						{
							name: "DEFAULT",
							views: ["Overview Private"],
						},
					]
				},

		},

**Comment by eouia** [comment]
use this into your target view configuration.

```js
slotTitleFormat:{
          sameDay: "[Heute]",
          nextDay: "[Morgen]",
          nextWeek: "dddd",
          lastDay: "[Gestern]",
          lastWeek: "[Letzen] ddd",
          sameElse: "MM/Do"
},
```

**Comment by M3taKn1ght** [comment]
Mam you saved my day! Special thanks to your support!

**Comment by M3taKn1ght** [comment]
okay, I tried your documentation and don't know how to fix the problem for a daily entry.
![IMG-20200512-WA0001](https://user-images.githubusercontent.com/15677429/81690234-4e9bf580-945b-11ea-9e82-e9979d47c6c2.jpg)
Currently I don't find the solution to translate this position....

**Comment by eouia** [comment]
that is `dateFormat`. override it as same with `slotTitleFormat`
