### ISSUE TITLE
Similar to issue 32

### ISSUE THREAD

**Issue by redy** [MMM-CalendarExt2/MMM-CalendarExt2#81]
I just realized that you had closed issue #32.

Hi, I seem to be having a similar issue. I followed the installation directions and the fix suggestions described in this issue.
1. Reinstall plugin
2. start in dev mode
3. Increase firstDrawingDelay.
I see nothing on the screen (i am able to see other modules).

I have this as my config.

		module: "MMM-CalendarExt2",
		config: {
			 rotateInterval: 90*1000,
			 firstDrawingDelay: 1000*10,
			 scenes: [ // `scenes` could have several scenes as elements of array
			 {
				   name: "My kids schedule",
				   views: ["Daily", "Weekly"],
				   //className: "CX2",
			 },

			],
			views: [
				{
				  name: "Daily",
				  mode: "upcoming",
				  calendars: ["Schedule"],
				  position: "top_center",
				  maxItems: 5,
				  maxDays: 1,
				  locale: "en",
				  hideOverflow: false,
				  filterPassedEvent: true,
				},
				{
				  name: "Weekly",
				  mode: "weekly",
				  position: "middle_center",
				  calendars: ["Schedule"],
				  type: "row",
				  slotCount: 5,
				  locale: "en",
				  hideOverflow: false,
				  filterPassedEvent: true,
				},
			  ],
			  calendars : [
				{
				  name: "Schedule",
				  icon: "noto-soccer-ball",
				  url: "https://calendar.google.com/calendar/ical/1d4a1djtgmai0fpapjvtr6cdhs%40group.calendar.google.com/public/basic.ics",
				  //url: "webcal://p23-caldav.icloud.com/published/2/MTU3Mzc5NzU3MTU3Mzc5N7QDyWhkoQhUDUPID--ipr-ZOrn-Q4_1aVyt-0MWrJp7YNRJozQcvp5txgCkR1Oa9aPtBd5BXqQ48ly68Sx7T98/"
				},
			  ],

		},
		  },

**Comment by klaernie** [comment]
Hi @redy, maybe the first question to ask: did you verify, that there are at least some events in the google calendar you used?

**Comment by redy** [comment]
Yes, there were. It was showing up with the calendar module included with the base magic mirror plugin.

**Comment by klaernie** [comment]
What do the logfiles say? Do they pickup the correct number of events?

**Comment by klaernie** [comment]
@redy I tested your config snipped and it works.

**Comment by klaernie** [comment]
no reply for a month, closing the issue
