### ISSUE TITLE
different SCENES in different PAGES?

### ISSUE THREAD

**Issue by thetobyde** [MMM-CalendarExt2/MMM-CalendarExt2#83]
Hey there. How can I trigger the Scenes? I use MMM-pages. In the first page I want to have the Upcoming view, in the secound page the Weekly mode. Is this possible? 
Toby :)

**Comment by klaernie** [comment]
Hi @thetobyde, the docs describe it here: https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/master/doc/Usage.md

The example is given for MMM-Page-Selector, so if you should be able to adapt it to MMM-Pages. Once you get it working feel free to send a PR for the docs with your example.
