### ISSUE TITLE
Day Format

### ISSUE THREAD

**Issue by thetobyde** [MMM-CalendarExt2/MMM-CalendarExt2#85]
Heyyy :) I was able to format my dates as I want except one thing:
If the event doas take the hole day, it formats like this: 6/20 ( 20. June)
I would like to chance this in German format like: 20. Juni.

Where I can change this? 

This is my config:
![Unbenannt](https://user-images.githubusercontent.com/53558782/84316416-64d8c680-ab6b-11ea-8a0d-e0c28b570f4f.JPG)

Thx mate! :)

**Comment by oresch** [comment]
Hi @thetobyde ,

have you tried playing with `dateFormat `instead of `dateTimeFormat`?

For example I'm using 
`slotSubTitleFormat: "Do.MMMM",
slotTitleFormat: {
sameDay: "[Heute]",
                                  nextDay: "[Morgen]",
                                  nextWeek: "dddd",
                                  lastDay: "[Gestern]",
                                  lastWeek: "[Last] ddd",
                                  sameElse: '"ddd, M/D"
                                },
                                dateFormat: {
                                        sameDay: "dddd",
                                },`

in my `daily` mode.
Maybe this is what you're lokking for?

**Comment by klaernie** [comment]
Thanks, @oresch for posting what I would have had to research!
