### ISSUE TITLE
Getting a "Same occurrence found twice, protecting you from death by recursion"

### ISSUE THREAD

**Issue by dagnis** [MMM-CalendarExt2/MMM-CalendarExt2#88]
Tried to add my wifes calendar and started getting this error. I have a different name, class name, and the url does give me a valid ics. 

I've checked to see if it's some weird glitch with recurring events by making one on my calendar, but didn't have the issue with just mine. Still have the issue with her calendar alone. We don't share or import each others calendar via google at all.

**Comment by klaernie** [comment]
Can you extract which event is causing this in her calendar, and produce an minimal ics that exihibts the problem? Else it’s kinda hard to fix the problem.

**Comment by dagnis** [comment]
> Can you extract which event is causing this in her calendar, and produce an minimal ics that exihibts the problem? Else it’s kinda hard to fix the problem.

Not sure of the best way to do that and what varuable is making an event a dub.

**Comment by dagnis** [comment]
Another thing I noticed since adding the google holiday calendar. When I use all 3, I only see mine, but when I comment out my wife's calendar I see the holiday and mine. It would seem my wife's somehow conflicts with the holiday? However, her's still doesn't work without the holiday. 

I've tried downloading the calendar and converting to csv in hopes of finding the vent. I've also deleted one event from the ics and compared the original text and the removed event text (in hopes something would be in the same line since everything was moved exactly one event up) but no dice.

**Comment by dagnis** [comment]
I'm closing the issue. I found where it's throwing the error in the node modules in ical.js within the build folder. It has a last compare to before. I had it print with the error message the last and before and found the event. It was a simple recurring event and there was no reason it's a duplicate event. The if check even has a "TODO is this valid?" note on it. commented it out. works fine now.
