### ISSUE TITLE
Change Cal Icons to lokas pictures

### ISSUE THREAD

**Issue by thetobyde** [MMM-CalendarExt2/MMM-CalendarExt2#90]
Hey :) is it possible to change the calendar icons to a lokal saved picture? I really want to use the Apple-Memojis instead of an icon from iconfy :D 

Maybe its possible to implement this? 
Thank you!

**Comment by thetobyde** [comment]
can you tell me where the icon is created? In the code? :)
Thx

**Comment by klaernie** [comment]
Well, the icons are created either [globally for the entire calendar ](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/master/docs/Configuration/Calendar.md)or using a [transform on the view](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/master/docs/Filtering-and-Sorting.md).

The use of iconify is hardcoded.
If you want to change that you'll need to:
- figure out how to get and generally use Apple-Memojis
- assign css classes to your events
- then use css `:before` selectors to insert the right HTML

Globally supporting this is probably too much effort for me, but if you make that modular and configurable I would accept a PR.
