### ISSUE TITLE
Filtering "if title contains"

### ISSUE THREAD

**Issue by smartroad** [MMM-CalendarExt2/MMM-CalendarExt2#91]
Hi!

I have a calendar that I would like to use (it has all the space launches in) but would only like it to show those on a Falcon 9. I have been looking at the filter option: 
`filter: (event) => {
  if (event.title == "WORK") return true
}`
but if i change "WORK" to "Falcon" I get to responses. I am guessing it is because it is looking for and exact match (hence the `==`) but the title is "Falcon 9 B5 • Starlink 539–595 & Blacksky Global 5–6". I am not up on how I can make it find a partial match, as the only constant between entries will be the "Falcon 9" at the beginning of the title, the rest will change depending on the mission.

Is there anyway I can make it so that it will only compare the first words or maybe just search within the title for the matching keywords?

(here is the calendar: https://calendar.google.com/calendar/embed?src=msacpn523mpjgq0jlooh41eme4@group.calendar.google.com)

**Comment by klaernie** [comment]
Hi @smartroad,

here is one of my filter functions:
```js
filter: (event) => {                         
    if (event.ms_busystatus == "TENTATIVE") {
        return false
    }                              
    if (event.title == "Blocker") {
        return false
    }                                      
    if (event.title == "Need to be home") {
        return false
    }                               
    if (event.title == "Vacation") {
        return false
    }                          
    if (event.title == "OoO") {
        return false
    }                                         
    if (event.title.startsWith("Canceled:")) {
        return false
    }          
    return true
},
```

Your problem can be solved with `event.title.match(/Falcon 9/)`.
But be aware: [once you solve a problem you now have two problems](https://blog.codinghorror.com/regular-expressions-now-you-have-two-problems/). So if you can rather use exact matches with `==`.
