### ISSUE TITLE
Calendar fading 

### ISSUE THREAD

**Issue by jleon12** [MMM-CalendarExt2/MMM-CalendarExt2#92]
Hello, I'm pretty new to this and I'm having an issue with my calendar where it fades and goes back to normal right away every two minutes. It started doing this right after I added the google photos  module. this is the code I'm using, any help is appreciated . 
```
	{
		  module: 'MMM-CalendarExt2',
		  config: {
			calendars : [
			  {
				name: "school",
				className: "school",
				url: "",
			  },
			],
			views: [
			  {
				name: "My weekly schedule",  
				mode: "week",
				slotCount: 7,
				maxItems: "1000",
				hideOverflow: false,
				monthFormat: "MMMM YYYY",
				slotMaxHeight:"95px",
				calendar: "school",
				position: "top_left",
			  },
			],
			scenes: [
			  {
				name: "DEFAULT",
			  },
			],
		  },
		},

```

```
{
  module: "MMM-GooglePhotos",
  position: "fullscreen_below",
  config: {
		albums: ["MagicMirror"],
		updateInterval: 1000*60*60*24,
		uploadAlbum: null, // Only album created by `create_uploadable_album.js`.
		condition: {
			fromDate: null, // Or "2018-03", RFC ... format available
			toDate: null, // Or "2019-12-25",
			minWidth: null, // Or 400
			maxWidth: null, // Or 8000
			minHeight: null, // Or 400
			maxHeight: null, // Or 8000
			minWHRatio: null,
			maxWHRatio: null,
			// WHRatio = Width/Height ratio ( ==1 : Squared Photo,   < 1 : Portraited Photo, > 1 : Landscaped Photo)
		},
		showWidth: 1080, // These values will be used for quality of downloaded photos to show. real size to show in your MagicMirror region is recommended.
		showHeight: 1920,
		timeFormat: "YYYY/MM/DD HH:mm", // Or `relative` can be used.
  }
},

```

![Calendar](https://user-images.githubusercontent.com/68558348/87964719-3f9b7a00-ca80-11ea-809a-b5a38b3eeb8f.gif)

**Comment by jleon12** [comment]
updateInterval on google photos  is 1000* 60* 60* 24, for some reason the * got removed when I posted the comment

**Comment by klaernie** [comment]
That looks for me much like the scene rotation/ update interval of CX2. Please take a look at https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/master/docs/Configuration/Others.md and see if you can vary the interval. 

I had CX2 running for a long time without the GPhotos module, and it always faded between the multiple scenes I had. Now you only have one scene, so it easily looks like fading in an out, with more then one scene one kind of expects this more.
