### ISSUE TITLE
Wiki images missing

### ISSUE THREAD

**Issue by Ofrty** [MMM-CalendarExt2/MMM-CalendarExt2#96]
Hi - the images on the repo's wiki aren't appearing. The dev tools show 404 errors when trying to pull from this path:

https://raw.githubusercontent.com/eouia/MMM-CalendarExt2/master/doc/<image-filename-here>

Cheers,
Joe

**Comment by Ofrty** [comment]
Hi - I realized that the images are all pointing to a "\doc\" subdirectory, but that subdirectory was renamed to "\docs\" (with a suffix -s) in a recent commit.

**Comment by KristjanESPERANTO** [comment]
I don't see any wiki here. This is no longer a current problem, is it? If it is, feel free to reopen the issue.
