### ISSUE TITLE
Vertical display not showing correctly

### ISSUE THREAD

**Issue by datamunk** [MMM-CalendarExt2/MMM-CalendarExt2#99]
Im having issues getting the calendar to show correctly with my monitor being vertical vs horizontal

It shows the "calendar" correct but the populated items are pretty much all missing. I confirmed this is the case by removing my custom.css code that rotates display

Rotate display code:

 body {
        margin: 0;
        position: absolute;
        transform: rotate(-90deg);
        transform-origin: top left;
        width: 100vh;
        height: 100vw;
        object-fit: cover;
        top: 100vh;
        visibility: visible;
 }

**Comment by datamunk** [comment]
Vertical with misalignment
![IMG_7425](https://user-images.githubusercontent.com/72761246/96004606-9c050000-0e09-11eb-9747-5010ee04aa09.jpg)

Horizontal and ok
![Screen Shot 2020-10-14 at 10 38 02 AM](https://user-images.githubusercontent.com/72761246/96004649-a921ef00-0e09-11eb-984b-6ae87baa6ba2.jpg)

**Comment by datamunk** [comment]
any ideas? I swear i had seen a page where someone had put a code in their custom.css to account for the rotation

**Comment by 3k9CP3bu4MoP** [comment]
Any particular reason for using the CSS to do the rotation rather than adding something like 'display_hdmi_rotate=3' to /boot/config.txt on the rpi?

**Comment by datamunk** [comment]
Honest answer? Cuz I dont know what I'm doing and googled how to rotate display, and thats what I had found and tried lol

**Comment by datamunk** [comment]
Also, I ended up going to calendarext module and making it kind of do what i want, more so than this module
